# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html
* Уэс Маккини. Python и анализ данных

## Задачи для совместного разбора

In [ ]:
import numpy as np

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [ ]:
arr = np.random.uniform(low = 0, high = 20, size = (4,7))
arr

array([[18.37120375,  8.29890376, 10.72961556,  6.66535262,  3.7338859 ,
         8.90885056, 16.64557306],
       [15.32660084, 15.73972452, 10.78268775, 14.86916682,  7.47219094,
         8.47079372,  2.472524  ],
       [ 5.63752304, 12.89268706,  7.76023399,  9.1984157 ,  6.12378585,
        19.38372498,  2.6702263 ],
       [10.59532751,  0.68921906, 13.06133692, 14.76516334, 14.48253993,
        17.11517993,  4.91379718]])

In [ ]:
#Normalization
arr = (arr - arr.min()) / (arr.max() - arr.min())
# Normalization: X = AX + B --> 1 / ptp(arr) * arr + (-arr.min()/ptp(arr))
arr

array([[0.94583857, 0.4070546 , 0.53707739, 0.31967325, 0.16286426,
        0.43968167, 0.85353173],
       [0.78297773, 0.8050764 , 0.53991631, 0.75850883, 0.36283237,
        0.41624928, 0.09539193],
       [0.26469295, 0.65278366, 0.37824027, 0.45517098, 0.29070395,
        1.        , 0.10596735],
       [0.5298941 , 0.        , 0.66180502, 0.75294551, 0.73782752,
        0.87865178, 0.22597966]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [ ]:
arr = np.random.randint(low = 0, high = 10, size = (8,10))
sum_by_row = arr.sum(axis = 0)
min_row_index = sum_by_row.argmin()
min_row_index, arr[min_row_index]

(2, array([2, 4, 1, 3, 0, 4, 6, 7, 9, 5]))

In [ ]:
arr[3, 4]

5

In [ ]:
arr[0:3, 4]

array([2, 9, 7])

In [ ]:
arr[:,4]

array([2, 9, 7, 5, 5, 1, 1, 6])

In [ ]:
sum_by_row = arr.sum(axis = 0)
sum_by_row

array([38, 37, 31, 39, 36, 41, 41, 33, 36, 39])

In [ ]:
min_row_index = sum_by_row.argmin()
arr[min_row_index]

array([5, 5, 2, 7, 7, 3, 4, 9, 1, 3])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [ ]:
x = np.array([1, 2, 3])
y = np.array([1, 0, 3])
np.sqrt(np.power(x - y, 2).sum())


2.0

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [ ]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])

In [ ]:
# @ - матричное умножение
X = np.linalg.inv(A) @ (-C) @ np.linalg.inv(B)
X

array([[ 1.00000000e+00,  5.32907052e-16],
       [-2.00000000e+00,  1.00000000e+00],
       [ 3.00000000e+00, -4.00000000e+00]])

## Лабораторная работа №1

In [237]:
#Read CSV and importing numpy
import numpy as np
data = np.loadtxt('C:/Users/Kyyot/Downloads/minutes_n_ingredients.csv', delimiter = ',', dtype = np.int32, skiprows = 1)
data

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,    140,     14]])

__При решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.__

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [149]:
data[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [150]:
print('Min minutes', np.min(data[1]))
print('Min ingr', np.min(data[2]), '\n')
print('Max minutes', np.max(data[1]))
print('Max ingr', np.max(data[2]), '\n')
print('Med minutes', np.median(data[1]))
print('Med ingr', np.median(data[1]))

Min minutes 7
Min ingr 6 

Max minutes 23891
Max ingr 94746 

Med minutes 25.0
Med ingr 25.0


3. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [151]:
np.random.choice(data[:,0], size = (10,3), replace = False)

array([[427706, 420944, 293328],
       [360539, 270346, 446714],
       [265641, 324352, 336755],
       [323240, 123380, 407831],
       [192834, 222868,  49036],
       [104436, 144417, 357473],
       [144665, 252714, 153857],
       [208631, 116781, 493999],
       [154387, 344032, 115255],
       [131948, 109575, 472948]])

4. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [152]:
data2 = data[data[:,2]<=5]
data2

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

5. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [153]:
percent = len(data[data[:,2]<=data[:,2].mean()])/len(data[:,2])*100
print('percentage of recipes', round(percent,2) ,'%')

percentage of recipes 58.8 %


6. Вычислите значение $q_{0.75}$ третьего квартиля продолжительности выполнения рецепта. Замените в этом столбце значения, большие чем $q_{0.75}$ на величину $q_{0.75}$.

In [154]:
quantile = np.quantile(data[:,1], q = 0.75)
data[data[:,1] > quantile] = quantile
quantile, data

(65.0,
 array([[127244,     60,     16],
        [ 23891,     25,      7],
        [ 94746,     10,      6],
        ...,
        [498432,     65,     15],
        [370915,      5,      4],
        [    65,     65,     65]]))

7. Посчитайте, для скольких рецептов исходного массива указана продолжительность, равная нулю. Модифицируйте исходный массив, заменив для таких строк значение в данном столбце на 1.

In [99]:
print(len(data[data[:,1]==0]))
data[data[:,1] == 0] = 1
data

479


array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [    65,     65,     65]])

8. Найдите множество возможных значений величины количества ингредиентов и количество вхождений каждого из уникальных значений в набор данных. Используя `numpy.isin`, выясните, какие числа из отрезка [1, 41] отсуствуют в данном множестве и выведите их на экран. 

In [211]:
un, count = np.unique(data[:,2], return_counts=True)
arr = np.array([un,count])
#print(arr.T)
test = np.arange(1,42)
mask = np.isin(arr, test)
print(arr[mask == False])

[   65   792  2547  4813  6726  7702  8495  8538  8149  7065  5844  4599
  3364  2341  1580  1062   685   416   284   175    91    64 24539]


9. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета.

In [114]:
max = np.max(data[:,2]/data[:,1])
print('Average = ', round(np.mean(data[:,2]/data[:,1]),2))
print('Max = ', max)

Average =  0.57
Max =  23.0


10. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [141]:
top100 = data[:,2][np.argsort(data[:,1])][::-100]
print(np.mean(top100))

21.884


11. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае. Выведите процент "простых" рецептов в датасете.

In [135]:
recipe = np.logical_and(data[:,1] <= 20, data[:,2] <=5).astype(int)
data = np.column_stack((data, np.transpose(recipe)))
data

array([[127244,     60,     16,      0,      0],
       [ 23891,     25,      7,      0,      0],
       [ 94746,     10,      6,      0,      0],
       ...,
       [498432,     65,     15,      0,      0],
       [370915,      5,      4,      1,      1],
       [    65,     65,     65,      0,      0]])

12. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет не менее 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [240]:
short = data[data[:,1] < 10]
stand = data[(data[:,1] >= 10) & (data[:,1] <= 20)]
long = data[data[:,1] > 20]
sh = [1 for i in range(len(short))]
st = [2 for i in range(len(stand))]
lg = [3 for i in range(len(long))]
res = sh + st + lg
data = np.column_stack((np.transpose(res), data[:,2].T ,data))
data.shape

(100000, 9)

13. Пусть в среднем одна минута работы повара стоит ресторану 5 ед., а средняя стоимость одного ингредиента составляет 10 ед. 
Создайте вектор-столбец `numpy`, содержащий данную информацию. Посчитайте среднюю стоимость приготовления для каждого из первых 10 рецептов в наборе данных.

In [220]:
money = 5*data[:,1] + 10*data[:,2]
avg = np.mean(5*data[:,1][:10] + 10*data[:,2][:10])
avg

216.0